---
kind: pipeline
name: default-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: rancher/dapper:v0.5.8
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    ref:
      include:
      - "refs/heads/main"
      - "refs/heads/v*"
    event:
    - push
    - pull_request

- name: release
  pull: default
  image: rancher/dapper:v0.5.8
  commands:
  - dapper ci
  privileged: true
  environment:
    CROSS: 1
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - tag

- name: stage-binaries-head
  image: rancher/dapper:v0.5.8
  commands:
  - "cp -r ./bin/kube-explorer ./package/"
  when:
    ref:
      include:
      - "refs/heads/main"
      - "refs/heads/v*"
    event:
    - push

- name: stage-binaries
  image: rancher/dapper:v0.5.8
  commands:
  - "cp -r ./bin/kube-explorer-linux-amd64 ./package/kube-explorer"
  when:
    event:
    - tag

- name: github_binary_release
  pull: default
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    files:
    - "bin/*"
    title: "${DRONE_TAG}"
    overwrite: true
  when:
    event:
    - tag

- name: docker-publish-head
  pull: default
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    context: package/
    password:
      from_secret: docker_password
    repo: cnrancher/kube-explorer
    tag: head-linux-amd64
    username:
      from_secret: docker_username
  when:
    ref:
      include:
      - "refs/heads/main"
      - "refs/heads/v*"
    event:
    - push

- name: docker-publish
  pull: default
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    context: package/
    password:
      from_secret: docker_password
    repo: cnrancher/kube-explorer
    tag: ${DRONE_TAG}-linux-amd64
    username:
      from_secret: docker_username
  when:
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

node:
  instance: agent-amd64

trigger:
  ref:
    include:
    - "refs/heads/main"
    - "refs/heads/v*"
    - "refs/tags/*"
  event:
    exclude:
    - promote

---
kind: pipeline
name: default-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  pull: default
  image: rancher/dapper:v0.5.8
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    ref:
      include:
      - "refs/heads/main"
      - "refs/heads/v*"
      - "refs/tags/*"
    event:
    - push
    - tag

- name: stage-binaries
  image: rancher/dapper:v0.5.8
  commands:
  - "cp -r ./bin/* ./package/"
  when:
    ref:
      include:
      - "refs/heads/main"
      - "refs/heads/v*"
      - "refs/tags/*"
    event:
    - push
    - tag

- name: docker-publish-head
  pull: default
  image: plugins/docker
  settings:
    build_args:
    - ARCH=arm64
    dockerfile: package/Dockerfile
    context: package/
    password:
      from_secret: docker_password
    repo: cnrancher/kube-explorer
    tag: head-linux-arm64
    username:
      from_secret: docker_username
  when:
    ref:
      include:
      - "refs/heads/main"
      - "refs/heads/v*"
    event:
    - push

- name: docker-publish
  pull: default
  image: plugins/docker
  settings:
    build_args:
    - ARCH=arm64
    dockerfile: package/Dockerfile
    context: package/
    password:
      from_secret: docker_password
    repo: cnrancher/kube-explorer
    tag: ${DRONE_TAG}-linux-arm64
    username:
      from_secret: docker_username
  when:
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

trigger:
  ref:
    include:
    - "refs/heads/main"
    - "refs/heads/v*"
    - "refs/tags/*"
  event:
    exclude:
    - promote

node:
  instance: agent-arm64

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: push-manifest-head
  image: plugins/manifest
  settings:
    ignore_missing: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest-head.tmpl
  when:
    ref:
      include:
      - "refs/heads/main"
      - "refs/heads/v*"
    event:
    - push

- name: push-manifest
  image: plugins/manifest
  settings:
    ignore_missing: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest.tmpl
  when:
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

node:
  instance: agent-amd64

trigger:
  ref:
    include:
    - "refs/heads/main"
    - "refs/heads/v*"
    - "refs/tags/*"
  event:
    exclude:
    - promote

depends_on:
- default-amd64
- default-arm64

...
