#!/bin/bash
set -e

source "$(dirname $0)/version"
cd "$(dirname $0)/.."

rm -rf ./bin/* ./dist/*

BUILD_TARGET="${BUILD_TARGET:-dev}"
CROSS=${CROSS:-}

if [[ $GITHUB_REF == refs/tags/* ]]; then
    CROSS=tag
fi

case "$CROSS" in
    "tag")
    BUILD_TARGET="prod"
    ;;
    "push")
    ;;
    *)
    BUILD_ARG="${BUILD_ARG} --single-target"
    ;;
esac

BUILD_ARG="${BUILD_ARG:-} --skip validate --id ${BUILD_TARGET}"

mkdir -p "./bin"

# upx is handled  by goreleaser
VERSION=${VERSION} COMMIT=${COMMIT} goreleaser build $BUILD_ARG

mkdir -p "./dist"

cp -r bin/kube-explorer-* dist/
