#!/bin/bash
set -e

cd "$(dirname $0)/.."
./scripts/download

source $(dirname $0)/version

[ "$(uname)" != "Darwin" ] && LINKFLAGS="-extldflags -static -s"

CGO_ENABLED=0 go build \
    -ldflags \
    "$LINKFLAGS" \
    -o bin/kube-explorer

