#!/bin/bash

mkdir -p $(dirname $GIT_SOURCE)

pushd $(dirname $GIT_SOURCE)

git clone --depth=1 --branch ${GIT_BRANCH} https://github.com/niusmallnan/steve.git
cd steve
git reset --hard ${GIT_COMMIT}

mkdir -p pkg/ui/ui/dashboard
cd pkg/ui/ui/dashboard
curl -sL https://rancher-dashboard-ui.s3.ap-southeast-2.amazonaws.com/release-2.5/${CATTLE_DASHBOARD_UI_VERSION}.tar.gz | tar xvzf - --strip-components=2
cp index.html ../index.html

popd

$(dirname $0)/hack_fs $GIT_SOURCE/pkg/ui/ui/
